Repository ethersphere/beekeeper, pull requests merged in 2020-11, with the labels that each got.

#63 fix address on created chunk
  pkg/bee/chunk.go
Labels: bug, pull-request

#62 Add pushsync check for files using tags
  cmd/beekeeper/cmd/check_pushsync.go
  pkg/bee/node.go
  pkg/beeclient/api/api.go
  pkg/beeclient/api/files.go
  pkg/beeclient/api/tags.go
  pkg/check/pushsync/pushsync.go
Labels: pull-request, ready for review

#64 add more chunks in gc check
  pkg/check/gc/chunk_notfound.go
Labels: pull-request

#67 Fix flaky tests
  pkg/bee/chunk.go
  pkg/check/pullsync/pullsync.go
  pkg/check/pushsync/pushsync.go
  pkg/check/retrieval/retrieval.go
Labels: bug, pull-request

#69 update actions/setup-go to v2
  .github/workflows/go.yml
Labels: pull-request

#68 retrieval test: download chunk instead of bytes
  pkg/check/retrieval/retrieval.go
Labels: pull-request

#65 pullsync: check only NN replication
  pkg/check/pullsync/pullsync.go
Labels: pull-request

#70 print name of every test that is executed from suite.sh
  scripts/suite.sh
Labels: pull-request
