Repository ethersphere/beekeeper, pull requests merged in 2021-01, with the labels that each got.

#78 Fix typo in fileHasher function
  pkg/bee/client.go
  pkg/bee/file.go
Labels: pull-request

#79 Fix map assignment
  pkg/bee/nodegroup.go
Labels: pull-request

#80 adjust dynamic kademlia check
  go.sum
  pkg/check/kademlia/dynamic.go
  pkg/check/kademlia/kademlia.go
Labels: pull-request, ready for review

#81 Improve k8s client error handling
  cmd/beekeeper/cmd/check_kademlia.go
  cmd/beekeeper/cmd/helpers.go
  pkg/bee/cluster.go
  pkg/bee/nodegroup.go
Labels: pull-request

#82 dynamic kademlia: dont check self
  pkg/check/kademlia/dynamic.go
Labels: bug, pull-request

#84 Dynamicpingpong
  cmd/beekeeper/cmd/check_kademlia.go
  cmd/beekeeper/cmd/check_pingpong.go
  pkg/bee/nodegroup.go
  pkg/check/chunkrepair/chunkrepair.go
  pkg/check/fileretrieval/fileretrieval.go
  pkg/check/kademlia/dynamic.go
  pkg/check/pingpong/dynamic.go
  pkg/check/pingpong/pingpong.go
  pkg/k8s/bee/node.go
Labels: pull-request

#85 Update clef to support latest image
  pkg/k8s/bee/helpers.go
  pkg/k8s/bee/node.go
Labels: pull-request

#86 Update bee config
  cmd/beekeeper/cmd/helpers.go
  pkg/k8s/bee/config.go
Labels: pull-request

#87 Remvoe index
  pkg/check/pushsync/pushsync.go
Labels: pull-request

#89 Add --in-cluster flag
  cmd/beekeeper/cmd/check.go
Labels: pull-request

#90 Add flag
  cmd/beekeeper/cmd/check.go
  cmd/beekeeper/cmd/print.go
Labels: pull-request

#91 Update pingpong
  pkg/bee/nodegroup.go
  pkg/check/pingpong/dynamic.go
  pkg/check/pingpong/pingpong.go
Labels: pull-request
